version: '2'
services:
  identity-mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - /home/docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"

  identity-provider:
    image: paymenthubee.azurecr.io/phee/identity-provider
    ports:
      - 5000:5000
    environment:
      FINERACT_DATASOURCE_CORE_HOST: identity-mysql
    depends_on:
      - identity-mysql
